[package]
name = "net-lattice-backend-linux"
version = "0.19.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true
description = "Linux backend for Net Lattice: implements net-lattice-platform's provider traits via Netlink."
readme = "README.md"

[features]
async = ["net-lattice-platform/async"]

[target.'cfg(target_os = "linux")'.dependencies]
net-lattice-core = { workspace = true }
net-lattice-ip = { workspace = true }
net-lattice-model = { workspace = true }
net-lattice-platform = { workspace = true }

tokio = { workspace = true, features = ["rt-multi-thread"] }
futures = { workspace = true }

rtnetlink = { workspace = true }
